default:
  tags:
    - docker-shared

stages:
  - build

build-push-case-1:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - docker build -t $DOCKER_LOGIN/myairflow:$CI_COMMIT_SHORT_SHA -t $DOCKER_LOGIN/myairflow:latest .
    - docker push $DOCKER_LOGIN/myairflow:$CI_COMMIT_SHORT_SHA
    - docker push $DOCKER_LOGIN/myairflow:latest
  only:
    - /^feature\//

build-push-case-2:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - docker build -t $DOCKER_LOGIN/myairflow:$CI_PIPELINE_ID .
    - docker push $DOCKER_LOGIN/myairflow:$CI_PIPELINE_ID
  only:
    variables:
      - $CI_COMMIT_TITLE =~ /^Merge branch '.+' into 'main'$/

build-push-case-3:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - docker build -t $DOCKER_LOGIN/myairflow:$CI_COMMIT_TAG .
    - docker push $DOCKER_LOGIN/myairflow:$CI_COMMIT_TAG
  only:
  - tags
  except:
    - ^(?!main).+@
